module.exports = [
  {
    canonical: "uiux",
    category: "design",
    variants: [
      "uiux",
      "ui/ux",
      "ui ux",
      "ui-ux",
      "ux/ui",
      "ux ui",
      "ux-ui",
      "uiux design",
      "ui ux design",
      "ui/ux design",
      "ux/ui design",
      "uiux designing",
      "ui/ux designing",
      "ui ux designing",
      "uiux design tools",
      "ui ux design tools",
      "ui/ux design tools",
      "ux/ui design tools",
      "ui design",
      "ux design",
      "ui",
      "ux",
      "user interface",
      "user experience",
      "user interface design",
      "user experience design",
    ],
  },
  {
    canonical: "javascript",
    category: "frontend",
    variants: ["javascript", "js"],
  },
  {
    canonical: "typescript",
    category: "frontend",
    variants: ["typescript", "ts"],
  },
  {
    canonical: "node.js",
    category: "backend",
    variants: ["node", "nodejs", "node.js"],
  },
  {
    canonical: "react",
    category: "frontend",
    variants: ["react", "reactjs", "react.js"],
  },
  {
    canonical: "next.js",
    category: "frontend",
    variants: ["next", "nextjs", "next.js"],
  },
  {
    canonical: "vue",
    category: "frontend",
    variants: ["vue", "vuejs", "vue.js"],
  },
  {
    canonical: "angular",
    category: "frontend",
    variants: ["angular", "angularjs"],
  },
  {
    canonical: "redux",
    category: "frontend",
    variants: ["redux", "redux toolkit", "rtk"],
  },
  { canonical: "webpack", category: "frontend", variants: ["webpack"] },
  { canonical: "vite", category: "frontend", variants: ["vite"] },
  {
    canonical: "jquery",
    category: "frontend",
    variants: ["jquery", "j query"],
  },
  { canonical: "html", category: "frontend", variants: ["html", "html5"] },
  { canonical: "css", category: "frontend", variants: ["css", "css3"] },
  {
    canonical: "scss",
    category: "frontend",
    variants: ["scss", "sass", "sassy css"],
  },
  { canonical: "bootstrap", category: "frontend", variants: ["bootstrap"] },
  {
    canonical: "tailwind",
    category: "frontend",
    variants: ["tailwind", "tailwindcss"],
  },
  { canonical: "python", category: "backend", variants: ["python", "py"] },
  { canonical: "java", category: "backend", variants: ["java"] },
  {
    canonical: "spring boot",
    category: "backend",
    variants: ["spring boot", "springboot"],
  },
  { canonical: "php", category: "backend", variants: ["php"] },
  {
    canonical: "express",
    category: "backend",
    variants: ["express", "expressjs", "express.js"],
  },
  {
    canonical: "nestjs",
    category: "backend",
    variants: ["nestjs", "nest js", "nest.js"],
  },
  { canonical: "django", category: "backend", variants: ["django"] },
  { canonical: "flask", category: "backend", variants: ["flask"] },
  {
    canonical: "fastapi",
    category: "backend",
    variants: ["fastapi", "fast api"],
  },
  { canonical: "laravel", category: "backend", variants: ["laravel"] },
  {
    canonical: ".net",
    category: "backend",
    variants: [".net", "dotnet", "asp.net", "asp net"],
  },
  {
    canonical: "ruby on rails",
    category: "backend",
    variants: ["ruby on rails", "rails", "ror"],
  },
  {
    canonical: "mongodb",
    category: "database",
    variants: ["mongodb", "mongo", "mongo db"],
  },
  { canonical: "mysql", category: "database", variants: ["mysql", "my sql"] },
  {
    canonical: "postgresql",
    category: "database",
    variants: ["postgresql", "postgres", "postgre sql"],
  },
  {
    canonical: "sql",
    category: "database",
    variants: ["sql", "structured query language"],
  },
  {
    canonical: "sqlite",
    category: "database",
    variants: ["sqlite", "sqlite3"],
  },
  { canonical: "redis", category: "database", variants: ["redis"] },
  {
    canonical: "elasticsearch",
    category: "database",
    variants: ["elasticsearch", "elastic search", "elk"],
  },
  {
    canonical: "oracle",
    category: "database",
    variants: ["oracle", "oracle db"],
  },
  {
    canonical: "git",
    category: "tools",
    variants: ["git", "github", "gitlab", "bitbucket"],
  },
  {
    canonical: "jira",
    category: "tools",
    variants: ["jira", "atlassian jira"],
  },
  { canonical: "postman", category: "tools", variants: ["postman"] },
  {
    canonical: "swagger",
    category: "tools",
    variants: ["swagger", "openapi", "open api"],
  },
  {
    canonical: "linux",
    category: "tools",
    variants: ["linux", "ubuntu", "debian"],
  },
  {
    canonical: "docker",
    category: "devops",
    variants: ["docker", "dockerfile"],
  },
  {
    canonical: "kubernetes",
    category: "devops",
    variants: ["kubernetes", "k8s"],
  },
  { canonical: "jenkins", category: "devops", variants: ["jenkins"] },
  { canonical: "terraform", category: "devops", variants: ["terraform"] },
  { canonical: "ansible", category: "devops", variants: ["ansible"] },
  {
    canonical: "ci/cd",
    category: "devops",
    variants: [
      "ci/cd",
      "cicd",
      "ci cd",
      "continuous integration",
      "continuous delivery",
    ],
  },
  { canonical: "nginx", category: "devops", variants: ["nginx", "n ginx"] },
  {
    canonical: "aws",
    category: "cloud",
    variants: ["aws", "amazon web services"],
  },
  {
    canonical: "azure",
    category: "cloud",
    variants: ["azure", "microsoft azure"],
  },
  {
    canonical: "gcp",
    category: "cloud",
    variants: ["gcp", "google cloud", "google cloud platform"],
  },
  {
    canonical: "firebase",
    category: "cloud",
    variants: ["firebase", "fire base"],
  },
  {
    canonical: "supabase",
    category: "cloud",
    variants: ["supabase", "supa base"],
  },
  { canonical: "figma", category: "design", variants: ["figma"] },
  { canonical: "adobe xd", category: "design", variants: ["adobe xd", "xd"] },
  {
    canonical: "photoshop",
    category: "design",
    variants: ["photoshop", "adobe photoshop"],
  },
  {
    canonical: "illustrator",
    category: "design",
    variants: ["illustrator", "adobe illustrator"],
  },
  {
    canonical: "wireframing",
    category: "design",
    variants: ["wireframe", "wireframing", "wire framing"],
  },
  {
    canonical: "prototyping",
    category: "design",
    variants: ["prototype", "prototyping"],
  },
  {
    canonical: "user research",
    category: "design",
    variants: ["user research", "ux research", "research"],
  },
  {
    canonical: "seo",
    category: "marketing",
    variants: ["seo", "search engine optimization"],
  },
  {
    canonical: "digital marketing",
    category: "marketing",
    variants: ["digital marketing"],
  },
  {
    canonical: "content writing",
    category: "marketing",
    variants: ["content writing", "copywriting"],
  },
  {
    canonical: "social media marketing",
    category: "marketing",
    variants: ["social media marketing", "smm"],
  },
  {
    canonical: "email marketing",
    category: "marketing",
    variants: ["email marketing"],
  },
  {
    canonical: "google analytics",
    category: "marketing",
    variants: ["google analytics", "ga4", "ga"],
  },
  {
    canonical: "project management",
    category: "softskills",
    variants: ["project management", "pm"],
  },
  {
    canonical: "communication",
    category: "softskills",
    variants: ["communication", "communication skills"],
  },
  { canonical: "leadership", category: "softskills", variants: ["leadership"] },
  {
    canonical: "teamwork",
    category: "softskills",
    variants: ["teamwork", "team work", "collaboration"],
  },
  {
    canonical: "problem solving",
    category: "softskills",
    variants: ["problem solving", "problem-solving"],
  },
  {
    canonical: "time management",
    category: "softskills",
    variants: ["time management"],
  },
  {
    canonical: "critical thinking",
    category: "softskills",
    variants: ["critical thinking"],
  },
  {
    canonical: "adaptability",
    category: "softskills",
    variants: ["adaptability", "adaptable"],
  },
  {
    canonical: "customer support",
    category: "support",
    variants: ["customer support", "technical support"],
  },
  {
    canonical: "networking",
    category: "support",
    variants: ["networking", "network administration", "network admin"],
  },
  {
    canonical: "windows os",
    category: "support",
    variants: ["windows", "windows os"],
  },
  {
    canonical: "hardware troubleshooting",
    category: "support",
    variants: ["hardware troubleshooting", "hardware support"],
  },
  { canonical: "sales", category: "business", variants: ["sales"] },
  {
    canonical: "business analysis",
    category: "business",
    variants: ["business analysis", "business analyst", "ba"],
  },
  {
    canonical: "agile",
    category: "business",
    variants: ["agile", "scrum", "kanban"],
  },
  {
    canonical: "data analysis",
    category: "data",
    variants: ["data analysis", "data analytics"],
  },
  {
    canonical: "power bi",
    category: "data",
    variants: ["power bi", "powerbi", "microsoft power bi"],
  },
  { canonical: "tableau", category: "data", variants: ["tableau"] },
  {
    canonical: "machine learning",
    category: "data",
    variants: ["machine learning", "ml"],
  },
  {
    canonical: "deep learning",
    category: "data",
    variants: ["deep learning", "dl"],
  },
];
